Repository googleapis/java-container, pull requests merged in 2020-09, with the labels that each got.

#227 test: fix build
  google-cloud-container/src/test/java/com/google/cloud/container/v1/it/ITSystemTest.java
Labels: api: container, cla: yes

#216 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: container, automerge, cla: yes, context: full

#228 chore: regenerate README
  README.md
  synth.metadata
Labels: api: container, cla: yes, context: none

#230 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .github/workflows/samples.yaml
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#231 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#232 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: container, automerge, cla: yes

#233 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: container, automerge, cla: yes, context: full

#234 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#235 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#236 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
