Repository googleapis/java-container, pull requests merged in 2020-12, with the labels that each got.

#315 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#317 chore: Update CODEOWNERS
  .github/CODEOWNERS
  .repo-metadata.json
Labels: cla: yes

#320 chore: migrate to microgenerator
  .github/CODEOWNERS
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerClient.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/package-info.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStub.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStubSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/GrpcClusterManagerCallableFactory.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/GrpcClusterManagerStub.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerClientTest.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerSmokeTest.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/MockClusterManager.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/MockClusterManagerImpl.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#321 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#322 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#332 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#333 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#334 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: cla: yes, context: full
