Repository googleapis/java-container, pull requests merged in 2020-06, with the labels that each got.

#174 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#166 fix: restore retry config for deleteCluster, deleteNode
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerClient.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/package-info.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStub.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStubSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/GrpcClusterManagerStub.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#177 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#180 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#179 docs: fix a broken link in the docs.
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/Cluster.java
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ClusterOrBuilder.java
  proto-google-cloud-container-v1/src/main/proto/google/container/v1/cluster_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#182 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#188 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#183 docs: Fixed broken links in the reference documentation
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodePool.java
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/NodePoolOrBuilder.java
  proto-google-cloud-container-v1/src/main/proto/google/container/v1/cluster_service.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#192 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#196 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#202 fix: migrate to grpc_service_config
  README.md
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerClient.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/ClusterManagerSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/package-info.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStub.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStubSettings.java
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/GrpcClusterManagerStub.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#206 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-container/pom.xml
  grpc-google-cloud-container-v1/pom.xml
  pom.xml
  proto-google-cloud-container-v1/pom.xml
Labels: cla: yes

#205 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
