Repository googleapis/java-container, pull requests merged in 2021-06, with the labels that each got.

#467 feat: add gcf-owl-bot[bot] to ignoreAuthors
  .github/generated-files-bot.yml
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#469 chore: release gapic-generator-java v1.0.10
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#474 feat: support for NodeAutoprovisioning ImageType
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AutoprovisioningNodePoolDefaults.java
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/AutoprovisioningNodePoolDefaultsOrBuilder.java
  proto-google-cloud-container-v1/src/main/java/com/google/container/v1/ClusterServiceProto.java
  proto-google-cloud-container-v1/src/main/proto/google/container/v1/cluster_service.proto
  synth.metadata
Labels: cla: yes, context: full

#479 chore: release gapic-generator-java v1.0.12
  google-cloud-container/src/main/java/com/google/cloud/container/v1/stub/ClusterManagerStubSettings.java
  google-cloud-container/src/test/java/com/google/cloud/container/v1/ClusterManagerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#478 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-container-bom/pom.xml
  google-cloud-container/pom.xml
  owlbot.py
  pom.xml
  versions.txt
Labels: automerge, cla: yes

#483 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
